/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/IconInput`; params?: Router.UnknownInputParams; } | { pathname: `/components/NotesList`; params?: Router.UnknownInputParams; } | { pathname: `/context/NotesContext`; params?: Router.UnknownInputParams; } | { pathname: `/sandbox/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/sandbox/Working`; params?: Router.UnknownInputParams; } | { pathname: `/stores/Counter`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/IconInput`; params?: Router.UnknownOutputParams; } | { pathname: `/components/NotesList`; params?: Router.UnknownOutputParams; } | { pathname: `/context/NotesContext`; params?: Router.UnknownOutputParams; } | { pathname: `/sandbox/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/sandbox/Working`; params?: Router.UnknownOutputParams; } | { pathname: `/stores/Counter`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/IconInput${`?${string}` | `#${string}` | ''}` | `/components/NotesList${`?${string}` | `#${string}` | ''}` | `/context/NotesContext${`?${string}` | `#${string}` | ''}` | `/sandbox/LoginScreen${`?${string}` | `#${string}` | ''}` | `/sandbox/Working${`?${string}` | `#${string}` | ''}` | `/stores/Counter${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/IconInput`; params?: Router.UnknownInputParams; } | { pathname: `/components/NotesList`; params?: Router.UnknownInputParams; } | { pathname: `/context/NotesContext`; params?: Router.UnknownInputParams; } | { pathname: `/sandbox/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/sandbox/Working`; params?: Router.UnknownInputParams; } | { pathname: `/stores/Counter`; params?: Router.UnknownInputParams; };
    }
  }
}
