/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/ForgotPassword` | `/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/LinkText` | `/LinkText`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/NetworkChecker` | `/NetworkChecker`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignIn` | `/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignUp` | `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/agent_screen`; params?: Router.UnknownInputParams; } | { pathname: `/modal/ModalItems`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/news_screen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/ChatPage`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Documents`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Reminders`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/pages`; params?: Router.UnknownInputParams; } | { pathname: `/upload_screen/Upload`; params?: Router.UnknownInputParams; } | { pathname: `/upload_screen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/ForgotPassword` | `/ForgotPassword`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/LinkText` | `/LinkText`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/NetworkChecker` | `/NetworkChecker`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/SignIn` | `/SignIn`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/SignUp` | `/SignUp`; params?: Router.UnknownOutputParams; } | { pathname: `/agent_screen`; params?: Router.UnknownOutputParams; } | { pathname: `/modal/ModalItems`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/news_screen`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/ChatPage`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/Documents`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/Reminders`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/Settings`; params?: Router.UnknownOutputParams; } | { pathname: `/pages`; params?: Router.UnknownOutputParams; } | { pathname: `/upload_screen/Upload`; params?: Router.UnknownOutputParams; } | { pathname: `/upload_screen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/ForgotPassword${`?${string}` | `#${string}` | ''}` | `/ForgotPassword${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/LinkText${`?${string}` | `#${string}` | ''}` | `/LinkText${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/NetworkChecker${`?${string}` | `#${string}` | ''}` | `/NetworkChecker${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/SignIn${`?${string}` | `#${string}` | ''}` | `/SignIn${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/SignUp${`?${string}` | `#${string}` | ''}` | `/SignUp${`?${string}` | `#${string}` | ''}` | `/agent_screen${`?${string}` | `#${string}` | ''}` | `/modal/ModalItems${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/news_screen${`?${string}` | `#${string}` | ''}` | `/pages/ChatPage${`?${string}` | `#${string}` | ''}` | `/pages/Documents${`?${string}` | `#${string}` | ''}` | `/pages/Reminders${`?${string}` | `#${string}` | ''}` | `/pages/Settings${`?${string}` | `#${string}` | ''}` | `/pages${`?${string}` | `#${string}` | ''}` | `/upload_screen/Upload${`?${string}` | `#${string}` | ''}` | `/upload_screen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/ForgotPassword` | `/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/LinkText` | `/LinkText`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/NetworkChecker` | `/NetworkChecker`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignIn` | `/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignUp` | `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/agent_screen`; params?: Router.UnknownInputParams; } | { pathname: `/modal/ModalItems`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/news_screen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/ChatPage`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Documents`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Reminders`; params?: Router.UnknownInputParams; } | { pathname: `/pages/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/pages`; params?: Router.UnknownInputParams; } | { pathname: `/upload_screen/Upload`; params?: Router.UnknownInputParams; } | { pathname: `/upload_screen`; params?: Router.UnknownInputParams; };
    }
  }
}
