/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/ForgotPassword` | `/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/LinkText` | `/LinkText`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/NetworkChecker` | `/NetworkChecker`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignIn` | `/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignUp` | `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/components/IconInput`; params?: Router.UnknownInputParams; } | { pathname: `/components/NotesList`; params?: Router.UnknownInputParams; } | { pathname: `/components/UIButton`; params?: Router.UnknownInputParams; } | { pathname: `/context/NotesContext`; params?: Router.UnknownInputParams; } | { pathname: `/sandbox/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/sandbox/Working`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Documents`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Reminders`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/screens`; params?: Router.UnknownInputParams; } | { pathname: `/stores/Counter`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/ForgotPassword` | `/ForgotPassword`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/LinkText` | `/LinkText`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/NetworkChecker` | `/NetworkChecker`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/SignIn` | `/SignIn`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(auth)'}/SignUp` | `/SignUp`; params?: Router.UnknownOutputParams; } | { pathname: `/components/IconInput`; params?: Router.UnknownOutputParams; } | { pathname: `/components/NotesList`; params?: Router.UnknownOutputParams; } | { pathname: `/components/UIButton`; params?: Router.UnknownOutputParams; } | { pathname: `/context/NotesContext`; params?: Router.UnknownOutputParams; } | { pathname: `/sandbox/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/sandbox/Working`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Documents`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Reminders`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/Settings`; params?: Router.UnknownOutputParams; } | { pathname: `/screens`; params?: Router.UnknownOutputParams; } | { pathname: `/stores/Counter`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/ForgotPassword${`?${string}` | `#${string}` | ''}` | `/ForgotPassword${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/LinkText${`?${string}` | `#${string}` | ''}` | `/LinkText${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/NetworkChecker${`?${string}` | `#${string}` | ''}` | `/NetworkChecker${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/SignIn${`?${string}` | `#${string}` | ''}` | `/SignIn${`?${string}` | `#${string}` | ''}` | `${'/(auth)'}/SignUp${`?${string}` | `#${string}` | ''}` | `/SignUp${`?${string}` | `#${string}` | ''}` | `/components/IconInput${`?${string}` | `#${string}` | ''}` | `/components/NotesList${`?${string}` | `#${string}` | ''}` | `/components/UIButton${`?${string}` | `#${string}` | ''}` | `/context/NotesContext${`?${string}` | `#${string}` | ''}` | `/sandbox/LoginScreen${`?${string}` | `#${string}` | ''}` | `/sandbox/Working${`?${string}` | `#${string}` | ''}` | `/screens/Documents${`?${string}` | `#${string}` | ''}` | `/screens/Reminders${`?${string}` | `#${string}` | ''}` | `/screens/Settings${`?${string}` | `#${string}` | ''}` | `/screens${`?${string}` | `#${string}` | ''}` | `/stores/Counter${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/ForgotPassword` | `/ForgotPassword`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/LinkText` | `/LinkText`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/NetworkChecker` | `/NetworkChecker`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignIn` | `/SignIn`; params?: Router.UnknownInputParams; } | { pathname: `${'/(auth)'}/SignUp` | `/SignUp`; params?: Router.UnknownInputParams; } | { pathname: `/components/IconInput`; params?: Router.UnknownInputParams; } | { pathname: `/components/NotesList`; params?: Router.UnknownInputParams; } | { pathname: `/components/UIButton`; params?: Router.UnknownInputParams; } | { pathname: `/context/NotesContext`; params?: Router.UnknownInputParams; } | { pathname: `/sandbox/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/sandbox/Working`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Documents`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Reminders`; params?: Router.UnknownInputParams; } | { pathname: `/screens/Settings`; params?: Router.UnknownInputParams; } | { pathname: `/screens`; params?: Router.UnknownInputParams; } | { pathname: `/stores/Counter`; params?: Router.UnknownInputParams; };
    }
  }
}
